name: sdl-course
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nodejs=22.13
  - git
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyterlab
  - pytest
  - ruff
  - python-docx
  - pydantic
  - pip:
      - uv
